version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8003:8003'
    depends_on:
      - redis
    environment:
      - TDENGINE_HOST=tdengine
      - TDENGINE_USER=root
      - TDENGINE_PASS=taosdata
      - TDENGINE_DB=farm_db

  redis:
    image: 'redis:alpine'
    ports:
      - '6380:6379'
